- about.html
- bus-ride.html
- christmas-party.html
- css/agency.min.css
- events.html
- featured-bajans.html
- gala.html
- give-kids.html
- index.html
- membership.html
- monthly-meetings.html
- photo-gallery.html
- picnic.html
- recipes.html
- recipes/desserts/cassava-pone.html
- recipes/latest-dessert.html
- recipes/latest-main.html
- scholarship.html
- second-harvest.html
- taste-of-barbados.html
- template.html
> Validated core html pages code using W3

- about.html
- events.html
- index.html
- template.html
> updating htmls with tags/spelling issues

- css/agency.min.css
- featured-bajans.html
- featured-bajans/dale-husbands.html
- featured-bajans/dennis-morris.html
Addresses issue #22 and other issues associated modal/popover for featured Bajans page, including:
- ensure modal content is read from remote file
- allow modal to be fullscreen
- allow user to close by clicking anywhere on the screen or using the close buttons at top & bottom
Note that: to test locally, will have to use Firefox browser (easiest option) or set up a local server with Apache.
> Addressed issue #22

- index.html
> addressed issue #33

- recipes.html
> removed reference to turnovers.html

- events.html
> updated text and removed download button

- about.html
- bus-ride.html
- christmas-party.html
- elections.html
- events.html
- featured-bajans.html
- gala.html
- give-kids.html
- index.html
- membership.html
- monthly-meetings.html
- photo-gallery.html
- picnic.html
- recipes.html
- scholarship.html
- second-harvest.html
- taste-of-barbados.html
- template.html
> updated footer text

- about.html
- css/agency.min.css
> changed design for "where we are section"

- css/agency.min.css
- photo-gallery.html
> fixed photo-gallery responsiveness

- featured-bajans/dale-husbands.html
> formatted text to aid with readability

- advertisement.html
- index.html
> updated ad to load full page

- about.html
- advertisement.html
- bus-ride.html
- christmas-party.html
- css/agency.min.css
- elections.html
- events.html
- featured-bajans.html
- gala.html
- give-kids.html
- index.html
- membership.html
- monthly-meetings.html
- monthly-meetings/june-2017.html
- photo-gallery.html
- picnic.html
- recipes.html
- scholarship.html
- second-harvest.html
- taste-of-barbados.html
- template.html
> fixed color scheme to meet W3AG color contrasts

- about.html
- index.html
> updated the dates manually

- about.html
- events.html
- index.html
- photo-gallery.html
- recipes.html
- recipes/main-courses/coucou.html
- made the map in the 'join us' section smaller
- added coming soon rubric to the recipes section instead of showing fake recipes except for one (to show the concept)
- cleaned up some text on the about and events pages
> added coming soon rubric and cleaned text

- about.html
- bus-ride.html
- christmas-party.html
- elections.html
- events.html
- featured-bajans.html
- gala.html
- give-kids.html
- index.html
- membership.html
- monthly-meetings.html
- photo-gallery.html
- picnic.html
- recipes.html
- scholarship.html
- second-harvest.html
- taste-of-barbados.html
- template.html
added 'Featured' to the front page (and the menu) to allow easy access to the Recipes and the Featured stories.
> improved navigation

- photo-gallery.html
> updated photo album to reflect all on FB

- monthly-meetings/june-2017.html
> added the new story

- about.html
- bus-ride.html
- christmas-party.html
- elections.html
- events.html
- featured-bajans.html
- gala.html
- give-kids.html
- index.html
- list-of-events.html
- membership.html
- monthly-meetings.html
- photo-gallery.html
- picnic.html
- recipes.html
- scholarship.html
- second-harvest.html
- stories.html
- taste-of-barbados.html
- template.html
> added twitter to menu bar

- about.html
- bus-ride.html
- christmas-party.html
- gala.html
- index.html
- js/contact_me.js
- mail/contact_me.php
- picnic.html
- taste-of-barbados.html
- updated where emails are to send according to the pages
- updated the email addresses
Addressing issue #76
> updated email related content

- about.html
- recipes/desserts/sweetbread.html
> updated image and link to latest recipe

- stories.html
- stories/duppy.html
- stories/gimme-de-way-it-was.html
> added CC license on stories

- about.html
partially addressing issue #52
> updated bio for treasurer

- photo-gallery.html
> updated with new album and fixed name of old album

- index.html
- mail/contact_me.php
> added phone number field

- index.html
> updated independence service info

- index.html
- taste-of-barbados.html
> advertising Taste of Barbados event

- events.html
> added gala to recently concluded event

- index.html
> added more info to the TOB event

- bus-ride.html
- christmas-party.html
- elections.html
- events.html
- featured-bajans.html
- gala.html
- give-kids.html
- index.html
- list-of-events.html
- membership.html
- monthly-meetings.html
- photo-gallery.html
- picnic.html
- recipes.html
- scholarship.html
- second-harvest.html
- stories.html
- taste-of-barbados.html
- template.html
Addressed issue #145 
Also updated photo album with Christmas party 2017
> updated copyright and photo album

- robots.txt
- sitemap.xml
> added accessibility for bots

- about.html
- index.html
> updated for irregular Feb meeting time

- about.html
- index.html
> updated date

- gala.html
> added gala 2018 album on feedback form

- about.html
- index.html
> updated with date for Dec meeting

- monthly-meetings.html
- monthly-meetings/apr-2018.html
- monthly-meetings/aug-2017.html
- monthly-meetings/aug-2018.html
- monthly-meetings/dec-2017.html
- monthly-meetings/feb-2018.html
- monthly-meetings/jan-2018.html
- monthly-meetings/jul-2018.html
- monthly-meetings/july-2017.html
- monthly-meetings/jun-2018.html
- monthly-meetings/mar-2018.html
- monthly-meetings/may-2018.html
- monthly-meetings/nov-2017.html
- monthly-meetings/nov-2018.html
- monthly-meetings/oct-2017.html
- monthly-meetings/oct-2018.html
- monthly-meetings/sep-2017.html
- monthly-meetings/sep-2018.html
> added summary for Nov
